version: '3.8'

services:

  mariadb:
    build: requirements/mariadb
    image: inc_img_mariadb
    container_name: inc_mariadb
    restart: unless-stopped
    env_file: .env
    networks:
      - inc_network
    volumes:
      - inc_data_db:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    image: inc_img_wordpress
    container_name: inc_wordpress
    restart: unless-stopped
    env_file: .env
    networks:
      - inc_network
    volumes:
      - inc_data_wp:/var/www/html

  nginx:
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERT_DIR=${CERT_DIR}
        - CERT_SUBJ=${CERT_SUBJ}
    image: inc_img_nginx
    container_name: inc_nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inc_network
    volumes:
      - inc_data_wp:/var/www/html

networks:
  inc_network:
    name: inc_network

volumes:
  inc_data_db:
    name: inc_data_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DB}
  inc_data_wp:
    name: inc_data_wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_WP}
